apiVersion: v1
kind: Service
metadata:
  name: sgx-demoapp
  labels:
    run: sgx-demoapp
spec:
  type: NodePort
  ports:
  - port: 8100
    targetPort: 8080
  selector:
    app: sgx-demoapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sgx-demoapp
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sgx-demoapp
    spec:
      containers:
      - name: sgx-demoapppod
        image: naru014/kubernetessampleapp:61
        ports:
        - containerPort: 80
