apiVersion: v1
kind: Service
metadata:
  name: sgx-demo-app
  labels:
    run: sgx-demo-app
spec:
  type: NodePort
  ports:
  - port: 8200
    targetPort: 8080
  selector:
    app: sgx-demo-app
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: sgx-demo-app
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: Rolling
    rollingParams:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sgx-demo-app
    spec:
      containers:
      - name: sgx-demoapp-pod
        image: naru014/kubernetessampleapp:28
        ports:
        - containerPort: 80
          "env": [
             {
                "name": "DB_USER",
                 "value": "dbuser"
             },
             {
              name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbpassword
             }
           ]
