apiVersion: v1
kind: Service
metadata:
  name: sgx-demoapp
  labels:
    run: sgx-demoapp
spec:
  type: NodePort
  ports:
  - port: 8200
    targetPort: 8080
  selector:
    app: sgx-demoapp
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: sgx-demoapp
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: Rolling
    rollingParams:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sgx-demoapp
    spec:
      containers:
      - name: sgx-demoapppod
        image: naru014/kubernetessampleapp:63
        ports:
        - containerPort: 80
          
          

